version: '3'
services:
  app:
    image: python:3.9
    environment:
      - CLIENT_ID=296aa1afb12b455881b9dc7f09a7c9b4
      - CLIENT_SECRET=e6d14ab89b964ff09c97e7f6814d93c5
      - HOST=data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com
      - PORT=5439
      - USER=m_rodriguezdavila_coderhouse
      - PASSWORD=M8ibr661u7
      - DATABASE=data-engineer-database
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python Spotify-davila-top50v3.py"
